# - id: opa-fmt
#   name: OPA test
#   description: Runs OPA unit tests on all rego source files.
#   entry: hooks/opa-test.py
#   language: python
#   files: (.*)  #(\.rego)$

- id: opa-fmt
  name: OPA fmt
  description: Formats Rego policy using opa fmt
  entry: opa-fmt.sh
  language: script
  files: (\.rego)$